export type TFood = {
	id: number;
	name: string;
	serving_size: number;
	calories: string;
	total_fat: string;
	saturated_fat: string;
	cholesterol: string;
	sodium: string;
	choline: string;
	vitamin_a: string;
	vitamin_b12: string;
	vitamin_b6: string;
	vitamin_c: string;
	vitamin_d: string;
	vitamin_e: string;
	vitamin_k: string;
	calcium: string;
	copper: string;
	iron: string;
	magnesium: string;
	manganese: string;
	phosphorous: string;
	potassium: string;
	zinc: string;
	protein: string;
	glutamic_acid: string;
	glycine: string;
	carbohydrate: string;
	fiber: string;
	sugars: string;
	fructose: string;
	galactose: string;
	glucose: string;
	lactose: string;
	maltose: string;
	sucrose: string;
	fat: string;
	saturated_fatty_acids: string;
	fatty_acids_total_trans: string;
	alcohol: string;
	ash: string;
	caffeine: string;
	water: string;
};

export type TFoodRecommendationNutrients = {
	calories: number;
	carbohydrate: number;
	total_fat: number;
	cholesterol: number;
	protein: number;
	fiber: number;
	sugars: number;
	sodium: number;
	vitamin_d: number;
	calcium: number;
	iron: number;
	caffeine: number;
};

export type TFoodMinimal = {
	id: string;
	name: string;
	serving_size: number;
	calories: string;
	carbohydrate: string;
	total_fat: string;
	cholesterol: string;
	protein: string;
	fiber: string;
	sugars: string;
	sodium: string;
	vitamin_d: string;
	calcium: string;
	iron: string;
	caffeine: string;
};

